### ISSUE TITLE
Factory method should be lowercase

### ISSUE THREAD

**Issue by IvanSanchez** [pasichnykvasyl/Leaflet.BigImage#1]
As per Leaflet's conventions, the factory method should be named `L.control.bigImage` instead of `L.control.BigImage`.

**Comment by pasichnykvasyl** [comment]
Fixed

**Comment by IvanSanchez** [comment]
Tip: write `Fixes #1` instead of `Issue #1` in the commit comment (or the comment on a pull request) to automatically close issues (so I don't have to come here and click the "close" button). See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
