### ISSUE TITLE
readme details aren't up to date ?

### ISSUE THREAD

**Issue by ethan-oro** [pasichnykvasyl/Leaflet.BigImage#5]
the readme details need to be updated to include the following:

the location of the css/js files are:

<link rel="stylesheet" href="./node_modules/leaflet.bigimage/src/Leaflet.BigImage.css">
<script src="./node_modules/leaflet.bigimage/src/Leaflet.BigImage.js"></script>

the js function to be added is:

 L.control.BigImage().addTo(map)

I think these are the right things (or they are what i had to change them to be in order for them to work)

**Comment by pasichnykvasyl** [comment]
You used the plugin a little wrong)
If you downloaded it, then everything would have connected successfully

As far as I can see, you tried to connect via a Node js
